// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xXW2/bNhT+KwS3R8myHTdd/ebaWesudrI1WdEGQUFLxxYTiVRIKrYa+L8PJOVYF+YC",
	"rCkwrE+xeDmXj9/5zskdDnmacQZMSTy8wzKMISXm5yjLEhoSRTnTn5ngGQhFwWwykoL+G4EMBc3sITwn",
	"KSC+RCoGRCrXPQwbkmYJ4CEmWeZLELcg/G4Pe1gVmV6WSlC2wlsPZ0TFbdNjwjijIUmQ3t85ESB5LkJo",
	"eth5lkGvfwCDV4evffjtzcLv9aMDnwxeHfqD/uFhb9B7Peh2u9jDAkh0wpICD5XIwRGVDpmGjpw/2o0H",
	"0mZ5iocXeA0LmzP2cMiZIpSBwJcOP4qCsE6WJE8UHva9hsNTntCwQGcUhNtpaZMyBSsQ2ug3zuyz1S19",
	"0ctPvNcFzqW/Bql8/Vi7330dO1WQGqvtJOwCEYIUeLvV8N7kVECk7Rnq7AHdg8AXVxAq7OGNTyDz79/W",
	"PMnWqxLymErVJmX14fX3fYC/CljiIf4l2JM9KJkeVKz+BTLjTEI7BQ8z2KivGVnBV8WvgbXBPNPLaMkF",
	"EqAEhVvKVgZYfRPpmxppATJPlKzxFYoP2Zfx9HB6dVTM+ufd+dnng+NP54OTT1M1O/twPSt68Xxy3j8+",
	"+7OYX33ezCdHB/PJaD0bf3jTLqAG2jVMWljXUb3Pv4UsjdoJTydPlfoza2/JRUoUHuI8p5FLEX6KzbPE",
	"5hEt+a/rxzMV4kgILtrsDXnkwNIcRmavEu+g23UhADvLLhspSElWdV5M2S1JaIR0LYLUAiBICgqERD76",
	"W28ZqNDvhCbgZL1dcHs0e1V3sVKZHAZBudIJeRqYmGWwIJFfRlErNkF9AUsQwAylH5cRm395yiUj74Ek",
	"tpTq2P/rAout4edUjSIqd9DUhobK7bbtwpl9I0O9RNmSWz4xRULdgLbN5jwZz9BpQkJIgSk0Op1iDyc0",
	"hFJVrZLhUUbCGFC/o9UgF0nlAdfrdYeY7Q4Xq6C8K4Pj6fho/vHI73e6nVilia1vZdJoOrwFIW04tz2S",
	"ZDHp6dM8A0Yyiof4oNM1njX2Bq+g2TlXoNo46qaLSJIgneSoesMYF+ZjGpUnGwf2/MfDi6blGdnQNE8R",
	"y9OFVSWjDUhx3UxzoRWF6oM3OQj9XCWOKdnYnizpNzNTmJ5eG596up5Ta3/3RVn51a70rfdwX8/IirKd",
	"wLnCqYwH1Via3LrUXLad1oDd73Z3rAKmGoNMcCXt/L2398xpxsxIhrf1hE7+0GwYfEenVnYdrt6SewHU",
	"Pl/9CJ9TpkAwkiDb9xGUBz0s8zQlosBD/A4skWu019MAlw7ejwUQBYgY3tfbXJ329uCoduJR3p+YHyRB",
	"04lh2HcYply8NFPVE3w0j/SWR8VLUNG+076flO26UQW9l3C9n+l/VoKjEnbcZjXe6TO1nhDc0WhrKyMB",
	"5RhLJma9XSNoQSREiDOUM3qTA5pOWmVj7z5aNobVZpSok7pOqSrJn/inwiHCgx9NvzlH49Ld/52GO/o4",
	"aBjfD5bOoaQc7sIYwmujoa4JrM63d6De74fKF2rEpYcHVKeWfDUFe8EiZalvx8MAby+3/wQAAP//nOTm",
	"Xq0TAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
